\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[margin=0.5in,top=1in,bottom=0.75in]{geometry}
\usepackage{amsmath}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage[table]{xcolor}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
%\usepackage{threeparttable}
%\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
%\usepackage{makecell}

\usepackage{multicol}
\usepackage{graphicx}

\usepackage{fancyhdr}
\pagestyle{fancy}
\lhead{Astrovirus notes}
\rhead{last update: \today}

\begin{document}
%\SweaveOpts{concordance=TRUE}

<<echo=FALSE>>=
library(knitr)
#opts_chunk$set(fig.width=6,fig.height=3.5,size="footnotesize",fig.align='center',cache=FALSE,echo=TRUE)
opts_chunk$set(fig.width = 6, fig.height = 3.5, size = "footnotesize", fig.align = "center", cache = FALSE, echo = FALSE, warning=FALSE, message=FALSE)
@

<<message=FALSE, warning=FALSE>>=
library(tidyverse)
library(magrittr)
library(knitr)
library(kableExtra)
library(cowplot)
@

<<message=FALSE, warning=FALSE>>=
source("shared_functions.R")
@


\section*{Exploratory Graphics}

<<fig.width=8, fig.height=4>>=
data <- readr::read_delim("~/github/j23414/starrynight/ingest/results/metadata.tsv", delim="\t")
@

\subsection*{What is the genome length of astrovirus?}

The astrovirus genome is approximately 6 to 8kb in length.

<<fig.width=8, fig.height=3>>=
perc_length <- c(7000, 400, 1508, 2385)
diagnostic_length_plot(
  data=data,
  approx_length = 7000,
  binwidth = 20,
  percentage_y = 1000
) +
  ggplot2::geom_vline(xintercept = 7000, linetype = "dashed", color = "red") +
  ggplot2::geom_vline(xintercept = 326, linetype = "dashed", color = "blue") +
  ggplot2::geom_vline(xintercept = 348, linetype = "dashed", color = "green") +
  # ORF1b length
  ggplot2::geom_vline(xintercept = 1508, linetype = "dashed", color = "pink") +
  # ORF2 length
  ggplot2::geom_vline(xintercept = 2385, linetype = "dashed", color = "purple") +
  ggplot2::annotate("text", 
    x = perc_length + 20*1.5, 
    y = c(1500, 1500,1250, 1050),
    label = c("7000 WGS", "326 RdRp or 348 ORF2 fragment", "1508 ORF1b", "2385 ORF2"),
    hjust = -0.1,
    angle = 0,
    size = 3,
    color = c("red", "blue", "pink", "purple")
    )
@

What is the distribution by length and host type?

<<fig.width=8, fig.height=3.5, echo=TRUE>>=
cdata <- data %>%
  subset(., !is.na(date)) %>%
  subset(., date !="XXXX-XX-XX") %>%
  mutate(
    date_adjusted = lubridate::date(gsub("-XX", "-01", date)),
    col_year = substr(date, 1, 4),
    col_mon = substr(date, 6,7),
    col_day = substr(date, 9,10),
    len_category = case_when(length > 4000 ~ "e_WGS",
                             length > 1700 ~ "c_ORF2",
                             length > 1000 ~ "d_ORF1b",
                             length > 300 ~ "b_fragment",
                             TRUE ~ "a_tiny"),
    host_category = case_when(host %in% c("Homo sapiens") ~ "Z_Human",
                              is.na(host) ~ "NA",
                              TRUE ~ "A_Other"),
    host_length = paste0(host_category,"_",len_category)
  )

diagnostic_time_fill_plot_month(
  subset(cdata, col_year > 2019),
  margin_l=0.5, fill="len_category"
  )

cdata %>% filter(col_year > 2019) %>% group_by(len_category) %>% summarise(n = n(), .groups = "drop")

diagnostic_time_fill_plot_month(
  subset(cdata, col_year > 2019),
  margin_l=0.5, fill="host_category"
  )

@

Focused on human samples:

<<fig.width=8, fig.height=4>>=
diagnostic_time_fill_plot_month(
  subset(subset(cdata, host_category=="Z_Human"), col_year > 2019),
  margin_l=0.5,
  fill="host_length"
  )
@

Focused on "NA" samples:

<<fig.width=8, fig.height=4>>=
diagnostic_time_fill_plot_month(
  subset(subset(cdata, host_category=="NA"), col_year > 2019),
  margin_l=0.5,
  fill="host_length"
  )
@

Focused on "Other" samples:

<<fig.width=8, fig.height=4>>=
diagnostic_time_fill_plot_month(
  subset(subset(cdata, host_category=="A_Other"), col_year > 2019),
  margin_l=0.5,
  fill="host_length"
  )
@


\newpage

\subsection*{Who are the main submitters of sequence data?}


<<fig.width=8, fig.height=6>>=
top_x_author_table(
  data=data,
  top_x=25,
  authors="authors"
)
@

<<fig.width=8, fig.height=6>>=
top_x_author_table(
  data=data,
  top_x=25,
  authors="host"
)
@

<<eval=FALSE>>=
library(taxize)

unique_hosts <- data %>%
  subset(host!="NA") %>%
  subset(!is.na(host)) %>%
  select(host) %>%
  unique(.)

#db_download_ncbi()

taxids <- taxize::get_uid(unique_hosts$host)
unique_hosts$taxids = taxids

#lineages <- classification(taxids, db = "ncbi")

# Fetch the class name
class_result <- tax_name(sci = taxids, get = "class", db = "ncbi")

# View the result
print(class_result$class)

unique_hosts$scientific_name <- classification(
  sci_id = unique_hosts$taxids,
  get = "genus",
  db = "ncbi"
)

unique_hosts$scientific_name <- sapply(
  unique_hosts$taxids,
  function(x) {
    classification(x, db = "ncbi")[[1]]$name[1]
  }
)
@

\newpage

\subsection*{What is the host/composition in each cluster?}

<<>>=
host_table <- data %>%
  count(major_cluster, host, name = "n") %>%
  group_by(major_cluster) %>%
  arrange(desc(n), host) %>%
  summarise(
    cluster_size = sum(n),
    hosts = paste(host, collapse = ", "),
    .groups = "drop"
  ) %>%
  arrange(desc(cluster_size))

write_delim(host_table, "cluster_host_table.tsv", delim="\t")

host_table %>% subset(!is.na(major_cluster) & cluster_size>2) %>% kable
@


\end{document}