\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[margin=0.5in,top=1in,bottom=0.75in]{geometry}
\usepackage{amsmath}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage[table]{xcolor}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
%\usepackage{threeparttable}
%\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
%\usepackage{makecell}

\usepackage{multicol}
\usepackage{graphicx}

\usepackage{fancyhdr}
\pagestyle{fancy}
\lhead{Astrovirus notes}
\rhead{last update: \today}

\begin{document}
%\SweaveOpts{concordance=TRUE}

<<echo=FALSE>>=
library(knitr)
#opts_chunk$set(fig.width=6,fig.height=3.5,size="footnotesize",fig.align='center',cache=FALSE,echo=TRUE)
opts_chunk$set(fig.width = 6, fig.height = 3.5, size = "footnotesize", fig.align = "center", cache = FALSE, echo = FALSE, warning=FALSE, message=FALSE)
@

<<message=FALSE, warning=FALSE>>=
library(tidyverse)
library(magrittr)
library(knitr)
library(kableExtra)
library(cowplot)
@

<<message=FALSE, warning=FALSE>>=
source("shared_functions.R")
@


\section*{Exploratory Graphics}

<<fig.width=8, fig.height=4>>=
data <- readr::read_delim("~/github/j23414/starrynight/ingest/results/metadata.tsv", delim="\t")
@

\subsection*{What is the genome length of astrovirus?}

The astrovirus genome is approximately 6 to 8kb in length.

<<fig.width=8, fig.height=3>>=
perc_length <- c(7000, 400, 1508, 2385)
diagnostic_length_plot(
  data=data,
  approx_length = 7000,
  binwidth = 20,
  percentage_y = 1000
) +
  ggplot2::geom_vline(xintercept = 7000, linetype = "dashed", color = "red") +
  ggplot2::geom_vline(xintercept = 326, linetype = "dashed", color = "blue") +
  ggplot2::geom_vline(xintercept = 348, linetype = "dashed", color = "green") +
  # ORF1b length
  ggplot2::geom_vline(xintercept = 1508, linetype = "dashed", color = "pink") +
  # ORF2 length
  ggplot2::geom_vline(xintercept = 2385, linetype = "dashed", color = "purple") +
  ggplot2::annotate("text", 
    x = perc_length + 20*1.5, 
    y = c(1500, 1500,1250, 1050),
    label = c("7000 WGS", "326 RdRp or 348 ORF2 fragment", "1508 ORF1b", "2385 ORF2"),
    hjust = -0.1,
    angle = 0,
    size = 3,
    color = c("red", "blue", "pink", "purple")
    )
@

What is the distribution by length and host type?

<<fig.width=8, fig.height=3.5, echo=TRUE>>=
cdata <- data %>%
  subset(., !is.na(date)) %>%
  subset(., date !="XXXX-XX-XX") %>%
  mutate(
    date_adjusted = lubridate::date(gsub("-XX", "-01", date)),
    col_year = substr(date, 1, 4),
    col_mon = substr(date, 6,7),
    col_day = substr(date, 9,10),
    len_category = case_when(length > 4000 ~ "e_WGS",
                             length > 1700 ~ "c_ORF2",
                             length > 1000 ~ "d_ORF1b",
                             length > 300 ~ "b_fragment",
                             TRUE ~ "a_tiny"),
    host_category = case_when(host %in% c("Homo sapiens") ~ "Z_Human",
                              is.na(host) ~ "NA",
                              TRUE ~ "A_Other"),
    host_length = paste0(host_category,"_",len_category)
  )

diagnostic_time_fill_plot_month(
  subset(cdata, col_year > 2019),
  margin_l=0.5, fill="len_category"
  )

cdata %>% filter(col_year > 2019) %>% group_by(len_category) %>% summarise(n = n(), .groups = "drop")

diagnostic_time_fill_plot_month(
  subset(cdata, col_year > 2019),
  margin_l=0.5, fill="host_category"
  )

@

Focused on human samples:

<<fig.width=8, fig.height=4>>=
diagnostic_time_fill_plot_month(
  subset(subset(cdata, host_category=="Z_Human"), col_year > 2019),
  margin_l=0.5,
  fill="host_length"
  )
@

Focused on "NA" samples:

<<fig.width=8, fig.height=4>>=
diagnostic_time_fill_plot_month(
  subset(subset(cdata, host_category=="NA"), col_year > 2019),
  margin_l=0.5,
  fill="host_length"
  )
@

Focused on "Other" samples:

<<fig.width=8, fig.height=4>>=
diagnostic_time_fill_plot_month(
  subset(subset(cdata, host_category=="A_Other"), col_year > 2019),
  margin_l=0.5,
  fill="host_length"
  )
@


\newpage

\subsection*{Who are the main submitters of sequence data?}


<<fig.width=8, fig.height=6>>=
top_x_author_table(
  data=data,
  top_x=25,
  authors="authors"
)
@

<<fig.width=8, fig.height=6>>=
top_x_author_table(
  data=data,
  top_x=25,
  authors="host"
)
@

<<eval=FALSE>>=
library(taxize)

unique_hosts <- data %>%
  subset(host!="NA") %>%
  subset(!is.na(host)) %>%
  select(host) %>%
  unique(.)

#db_download_ncbi()

taxids <- taxize::get_uid(unique_hosts$host)
unique_hosts$taxids = taxids

#lineages <- classification(taxids, db = "ncbi")

# Fetch the class name
class_result <- tax_name(sci = taxids, get = "class", db = "ncbi")

# View the result
print(class_result$class)

unique_hosts$scientific_name <- classification(
  sci_id = unique_hosts$taxids,
  get = "genus",
  db = "ncbi"
)

unique_hosts$scientific_name <- sapply(
  unique_hosts$taxids,
  function(x) {
    classification(x, db = "ncbi")[[1]]$name[1]
  }
)
@

\newpage

\subsection*{What is the host/composition in each cluster?}

<<fig.width=8, fig.height=6>>=
host_table <- data %>%
  count(major_cluster2, host, name = "n") %>%
  group_by(major_cluster2) %>%
  arrange(desc(n), host) %>%
  summarise(
    cluster_size = sum(n),
    hosts = paste(host, "(",n,")", collapse = ", ", sep=""),
    .groups = "drop"
  ) %>%
  arrange(desc(cluster_size))

temp<-subset(data, !is.na(major_cluster2))

write_delim(host_table, "cluster_host_table.tsv", delim="\t")

host_table %>%
  subset(!is.na(major_cluster2) & cluster_size>2) %>%
  kable

# Roughly get host common names for samples in major clusters
plot_data <- data %>%
  subset(!is.na(major_cluster2)) %>%
  mutate(
    host=case_when(host=="Homo sapiens" ~ "humans",
                   host=="Sus scrofa" ~ "pig",
                   host=="Sus scrofa domesticus" ~ "pig",
                   host=="Anatidae" ~ "waterfowl", # ducks, swans
                   host=="Anser anser" ~ "waterfowl", #goose
                   host=="Anser" ~ "waterfowl", #goose
                   host=="Anser cygnoides" ~ "waterfowl",
                   host=="Anser sp." ~ "waterfowl",
                   host=="Anas platyrhynchos" ~ "waterfowl",
                   host=="Cairina moschata" ~ "waterfowl",
                   host=="Gallus gallus" ~ "chicken",
                   host=="Meleagris gallopavo" ~ "turkey",
                   host=="Capreolus capreolus"~"wild bird",
                   host=="Columba livia"~"wild bird",
                   host=="Columbidae"~"wild bird",
                   host=="Spilopelia chinensis"~"wild bird",
                   host=="Zalophus californianus" ~ "sea lion",
                   host=="Bos taurus" ~ "cattle",
                   host=="Bovidae"~"cattle",
                   host=="Bos grunniens"~"cattle",
                   host=="Bubalus bubalis"~"cattle",
                   host=="Chiroptera sp." ~ "bat",
                   host=="Feliformia" ~ "cat",
                   host=="Hipposideros armiger" ~ "bat",
                   host=="Hipposideros larvatus" ~ "bat",
                   host=="Marmota caudata" ~ "rat",
                   host=="Marmota sibirica" ~ "rat",
                   host=="Miniopterus fuliginosus" ~ "bat",
                   host=="Miniopterus minor" ~ "bat",
                   host=="Miniopterus sp. B76" ~ "bat",
                   host=="Miniopterus schreibersii" ~ "bat",
                   host=="Rattus tanezumi" ~ "rat",
                   host=="Rattus nitidus" ~ "rat",
                   host=="Rattus losea" ~ "rat",
                   host=="Myotis davidii" ~ "bat",
                   host=="Myotis sp." ~ "bat",
                   host=="Rhinolophus sp." ~ "bat",
                   host=="Camelus dromedarius"~"camel",
                   host=="Camelus bactrianus"~"camel",
                   host=="Capra hircus"~"goat",
                   host=="Budorcas tibetana"~"goat",
                   host=="Ovis aries"~"sheep",
                   host=="Ailurus fulgens" ~ "red panda",
                   host=="Aves" ~ "wild bird",
                   host=="Berylmys bowersi" ~ "rat",
                   host=="Bos mutus" ~ "cattle",
                   host=="Capreolus capreolus"~"deer",
                   host=="Rattus norvegicus" ~ "rat",
                   host=="Rattus andamanesis" ~ "rat",
                   host=="Mus musculus" ~ "mouse",
                   host=="Hystrix brachyura" ~ "rat",
                   host=="Rattus andamanensis" ~ "rat",
                   host=="Neogale vison"~"mink",
                   host=="Mustela lutreola"~"mink",
                   host=="Marmota himalayana"~"squirrel",
                   host=="Oryctolagus cuniculus"~"rabbit",
                   host=="Canis lupis familiaris" ~ "dog",
                   host=="Canis lupus familiaris" ~ "dog",
                   host=="Canis lupus" ~ "dog",
                   host=="Nyctereutues procyonoides" ~ "dog",
                   host=="Nyctereutes procyonoides" ~ "dog",
                   host=="Cerdocyon thous" ~ "fox",
                   host=="Felis catus" ~ "cat",
                   host=="Panthera tigris altaica" ~ "cat",
                   host=="Arnoglossus sp." ~ "fish",
                   host=="Echelus uropterus" ~ "fish", # eel
                   host=="Ptyas mucosa" ~ "snake",
                   host=="Suncus murinus" ~ "rat",
                   host=="Ovibos moschatus" ~ "cattle",
                   host=="Pipistrellus abramus" ~ "bat",
                   host=="Mustela putorius furo" ~ "mink",
                   host=="Phrynocephalus erythrurus" ~ "lizard",
                   host=="Myotis laniger" ~ "bat",
                   host=="Paguma larvata" ~ "mink",
                   host=="Neodon fuscus" ~ "cat",
                   is.na(host) ~ "Unknown",
                   TRUE ~ host)
  ) %>%
  count(major_cluster2, host, name = "n") %>%
  group_by(major_cluster2) %>%
  mutate(
    cluster_size = sum(n),
    host_proportion = n / cluster_size,
    host_percentage = 100 * n / cluster_size,
    ) %>%
  ungroup() %>%
  arrange(desc(cluster_size))

# unique(plot_data$host)
# Set the order and color palette of hosts
host_colors <- c(
  "humans"    = "#7F0000",
  "mouse"     = "#A50F15",
  "rat"       = "#CB181D",
  "bat"       = "#CB1855",
  "squirrel"  = "#EF3B2C",
  "rabbit"    = "#FB6A4A",
  "cat"       = "#FC9272",
  "dog"       = "#FCBBA1",
  "mink"      = "#FDD0A2",
  "fox"       = "#FDD055",
  "sea lion"  = "#FEE391",
  "red panda" = "#FEE388", 
  "pig"       = "#FED976",
  "cattle"    = "#FEB24C",
  "sheep"     = "#FD8D3C",
  "goat"      = "#F16913",
  "camel"     = "#D94801",
  "chicken"   = "#74C476",
  "turkey"    = "#41AB5D",
  "waterfowl" = "#238B45",
  "wild bird" = "#005A32",
  "lizard"    = "#1C9055",
  "snake"     = "#1C9099",
  "fish"      = "#2171B5"
)

order_host <- names(host_colors)

highest_order_host <- c(
  "Unknown",
  "bat",
  "squirrel",
  "rabbit",
  "fox",
  "sea lion",
  "red panda",
  "camel",
  "turkey",
  "lizard",
  "snake",
  "fish",
  "wild bird",
  "mouse",
  "rat",
  "goat",
  "sheep",
  "mink",
  "chicken",
  "cat",
  "cattle",
  "dog",
  "pig",
  "humans",
  "waterfowl"
)


plot_data <- plot_data %>%
  subset(., cluster_size > 2) %>%
  mutate(
    major_cluster2 = factor(major_cluster2, levels = unique(major_cluster2[order(-cluster_size)]))
  )

plot_data_filtered <- subset(plot_data, cluster_size >2)
plot_data_filtered$host <- factor(plot_data_filtered$host, levels=highest_order_host)

#unique(plot_data_filtered$host)

# Plot amounts along top, and proportion below
library(cowplot)

p1 <- ggplot(plot_data_filtered, aes(x = major_cluster2, y = n, fill=host)) +
  geom_col() +
  labs( x = NULL,y = "Number of samples") +
  theme_minimal() +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    legend.position="none"
  ) +
  scale_fill_manual(values = host_colors)


# Bottom: proportions, colored by host
p2 <- ggplot(plot_data_filtered, aes(x = major_cluster2, y = n, fill = host)) +
  geom_col(position = "fill") +
  labs(x = "Major cluster", y = "Proportion", fill = "Host") +
  scale_y_continuous(labels = scales::percent) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1),
    legend.position="bottom"
  )  +
  scale_fill_manual(values = host_colors)+
  guides(fill=guide_legend(nrow=3))
#p2

legend <- get_legend(p2)

p2 <- p2 + theme(legend.position = "none")

plots <- plot_grid(
  p1, p2,
  ncol = 1,
  align = "v",
  axis = "lr",
  rel_heights = c(5, 4)
)

plot_grid(
  plots, legend,
  ncol = 1,
  rel_heights = c(1, 0.15)
  #rel_widths = c(1, 0.15)
)
@

\section*{Request for a heatmap}

<<fig.width=11, fig.height=6>>=
# ggplot heatmap
plot_data_filtered %>%
subset(., cluster_size > 3) %>%
  ggplot(., aes(x=major_cluster2, y=host, fill=host_percentage)) + geom_tile() +
  scale_fill_gradient2(
    low = "white",
    mid = "#B7E4C7",
    high = "#2D6A4F",
    midpoint = median(plot_data_filtered$n, na.rm = TRUE)
  ) +
  geom_text(aes(label = n)) +
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1,vjust=0.5),
  )
@

<<fig.width=11, fig.height=6>>=
library(dplyr)
library(tidyr)
library(pheatmap)

heatmap_data <- plot_data_filtered %>%
  filter(cluster_size > 3) %>%
  select(major_cluster2, host, host_percentage) %>%
  pivot_wider(
    names_from = major_cluster2,
    values_from = host_percentage,
    values_fill = 0
  )

heatmap_matrix <- heatmap_data %>%
  column_to_rownames("host") %>%
  as.matrix()

number_data <- plot_data_filtered %>%
  filter(cluster_size > 3) %>%
  mutate(
    host = ifelse(is.na(host), "Unknown", host)
  ) %>%
  select(major_cluster2, host, n) %>%
  pivot_wider(
    names_from = major_cluster2,
    values_from = n,
    values_fill = 0
  )

number_matrix <- number_data %>%
  tibble::column_to_rownames("host") %>%
  as.matrix()

number_matrix <- ifelse(
  number_matrix == 0,
  "",
  as.character(number_matrix)
)

pheatmap(
  heatmap_matrix,
  cluster_cols = FALSE,
  cluster_rows = TRUE,
  scale = "none",
  color = colorRampPalette(c(
  "#FFFFFF", # 0%
  "#D9F0D3", # 25%
  "#FFFFBF", # 50%
  "#FEC44F", # 75%
  "#F4A261"  # 100%
  ))(100),
  display_numbers = number_matrix,
  number_format = "%.0f",
  border_color = "grey90"
)

pheatmap(
  heatmap_matrix,
  cluster_cols = TRUE,
  cluster_rows = TRUE,
  scale = "none",
  color = colorRampPalette(c(
  "#FFFFFF", # 0%
  "#D9F0D3", # 25%
  "#FFFFBF", # 50%
  "#FEC44F", # 75%
  "#F4A261"  # 100%
  ))(100),
  display_numbers = number_matrix,
  number_format = "%.0f",
  border_color = "grey90"
)
@

\end{document}