\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[margin=0.5in,top=1in,bottom=0.75in]{geometry}
\usepackage{amsmath}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage[table]{xcolor}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}

\usepackage{multicol}
\usepackage{graphicx}

\usepackage{fancyhdr}
\pagestyle{fancy}
\lhead{Mumps notes}
\rhead{last update: \today}

\begin{document}

<<,echo=FALSE>>=
#opts_chunk$set(fig.width=6,fig.height=3.5,size="footnotesize",fig.align='center',cache=FALSE,echo=TRUE)
opts_chunk$set(fig.width = 6, fig.height = 3.5, size = "footnotesize", fig.align = "center", cache = FALSE, echo = FALSE, warning=FALSE, message=FALSE)
@

<<message=FALSE, warning=FALSE>>=
source("shared_functions.R")
@

\section*{Background}

\section*{Exploratory Graphics}

<<fig.width=8, fig.height=3>>=
pathogen <- "mumps"

# Download and decompress file
data_file=paste0(pathogen, "/metadata.tsv")
if (!file.exists(paste0(pathogen, "/metadata.tsv"))) {
  system(paste("mkdir -p ", pathogen, sep=""))
  file_name <- "metadata.tsv"
  zst_file <- paste0(file_name, ".zst")
  url <- paste0("https://data.nextstrain.org/files/workflows/", pathogen, "/metadata.tsv.zst")
  system(paste0("curl -L ", url, " -o ", pathogen,"/", zst_file))
  system(paste0("zstd -d ", pathogen, "/", zst_file, " -o ", pathogen, "/", file_name))
}

data <- readr::read_delim(paste0(pathogen, "/metadata.tsv"), delim="\t")
@

\section*{NCBI GenBank records}

<<fig.width=8, fig.height=2.5>>=
diagnostic_length_plot(
  data = data,
  approx_length = 15384,
  binwidth = 200,
  percentage_y = 9000
)

diagnostic_length_plot(
  data = data %>% subset(length<500),
  approx_length = 315,
  binwidth = 20,
  percentage_y = 9000
)
@

\section*{SH gene}

\textbf{Missing Data}


<<fig.width=8, fig.height=2.5>>=
SH_NEXTCLADE='~/Desktop/debug/fixup-config-and-logs/ingest/results/sh/nextclade.tsv'

data <- readr::read_delim(SH_NEXTCLADE, delim="\t")

# names(data)

data %>%
  ggplot(. , aes(x=clade, y=totalMissing)) +
  geom_violin() +
  geom_boxplot(width=0.5) +
  theme_bw()
@


\textbf{Mixed Sites (M)}

<<fig.width=8, fig.height=2.5>>=
data %>%
  ggplot(. , aes(x=clade, y=totalNonACGTNs)) +
  geom_violin() +
  geom_boxplot() +
  theme_bw()
@

\textbf{Private Mutations}

<<fig.width=8, fig.height=2.5>>=
data %>%
  ggplot(. , aes(x=clade, y=privateNucMutations.totalLabeledSubstitutions)) +
  geom_violin() +
  geom_boxplot() +
  theme_bw()

data %>%
  ggplot(. , aes(x=clade, y=privateNucMutations.totalUnlabeledSubstitutions)) +
  geom_violin() +
  geom_boxplot() +
  theme_bw()

data %>%
  ggplot(. , aes(x=clade, y=privateNucMutations.totalReversionSubstitutions)) +
  geom_violin() +
  geom_boxplot() +
  theme_bw()

data %>%
  ggplot(. , aes(x=clade, y=privateNucMutations.totalPrivateSubstitutions)) +
  geom_violin() +
  geom_boxplot() +
  theme_bw()
@



\end{document}