\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[margin=0.5in,top=1in,bottom=0.75in]{geometry}
\usepackage{amsmath}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage[table]{xcolor}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}

\usepackage{multicol}
\usepackage{graphicx}

\usepackage{fancyhdr}
\pagestyle{fancy}
\lhead{Mumps notes}
\rhead{last update: \today}

\begin{document}

<<,echo=FALSE>>=
#opts_chunk$set(fig.width=6,fig.height=3.5,size="footnotesize",fig.align='center',cache=FALSE,echo=TRUE)
opts_chunk$set(fig.width = 6, fig.height = 3.5, size = "footnotesize", fig.align = "center", cache = FALSE, echo = FALSE, warning=FALSE, message=FALSE)
@

<<message=FALSE, warning=FALSE>>=
source("shared_functions.R")
@

\section*{Background}

\section*{Exploratory Graphics}

<<fig.width=8, fig.height=3>>=
pathogen <- "mumps"

# Download and decompress file
data_file=paste0(pathogen, "/metadata.tsv")
if (!file.exists(paste0(pathogen, "/metadata.tsv"))) {
  system(paste("mkdir -p ", pathogen, sep=""))
  file_name <- "metadata.tsv"
  zst_file <- paste0(file_name, ".zst")
  url <- paste0("https://data.nextstrain.org/files/workflows/", pathogen, "/metadata.tsv.zst")
  system(paste0("curl -L ", url, " -o ", pathogen,"/", zst_file))
  system(paste0("zstd -d ", pathogen, "/", zst_file, " -o ", pathogen, "/", file_name))
}

data <- readr::read_delim(paste0(pathogen, "/metadata.tsv"), delim="\t")
@

\section*{NCBI GenBank records}

<<fig.width=8, fig.height=2.5>>=
diagnostic_length_plot(
  data = data,
  approx_length = 15384,
  binwidth = 200,
  percentage_y = 9000
)
@

<<fig.width=8, fig.height=4>>=
diagnostic_time_fill_plot(
  data=data,
  fill="region"
)
@

<<fig.width=8, fig.height=4>>=
diagnostic_time_fill_plot(
  data=data,
  fill="MuV_genotype",
  title="MuV Genotype",
  rel_heights = c(2.5,7)
)
@

<<fig.width=8, fig.height=4>>=
diagnostic_time_fill_plot(
  data=data,
  fill="MuV_genotype_nextclade",
  title="MuV Genotype_nextclade",
  rel_heights = c(2.5,7)
)
@

\newpage
\section*{Nextclade dataset}

<<fig.width=5, fig.height=5>>=
# Pivot Table comparing MuV_genotype and MuV_genotype_nextclade columns
pivot <- data %>%
  count(MuV_genotype, MuV_genotype_nextclade) %>%
  complete(MuV_genotype, MuV_genotype_nextclade, fill = list(n = 0)) %>%
  mutate(
    log_n = ifelse(n > 0, log10(n), NA),
    MuV_genotype = case_when(is.na(MuV_genotype) ~ "NA",
                             TRUE ~ MuV_genotype),
    MuV_genotype = fct_rev(factor(MuV_genotype))
  )

# Plot
ggplot(pivot, aes(x = MuV_genotype_nextclade, y = MuV_genotype, fill = log_n)) +
  geom_tile(color = "white") +
  geom_text(aes(label = ifelse(n > 0, as.character(n), "")), color = "black", size = 3) +
  scale_fill_gradient(
    low = "white", high = "orange",
    na.value = "white"
  ) +
  scale_y_discrete(name = "Original MuV Genotype from GenBank") +
  scale_x_discrete(name = "Nextclade MuV Genotype results", position = "top") +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 0, vjust = 0.5),
  )
@

<<>>=
mismatch <- data %>%
  subset(MuV_genotype != MuV_genotype_nextclade) %>%
  subset(!(MuV_genotype %in% c("G1", "G2") & MuV_genotype_nextclade %in% c("G"))) %>%
  subset(!(MuV_genotype %in% c("H1", "H2") & MuV_genotype_nextclade %in% c("H"))) %>%
  subset(!(MuV_genotype %in% c("K/M", "M") & MuV_genotype_nextclade %in% c("K"))) %>%
  select(c("accession", "strain","length", "genotype", "MuV_genotype", "MuV_genotype_nextclade")) %>%
  arrange(MuV_genotype)

kable(mismatch, caption = "Mismatched Genotype between GenBank and Nextclade datasets") %>%
    kable_styling(
      latex_options = c("hold_position", "striped")
    )

@

\newpage

<<fig.width=8, fig.height=3>>=
top_x_author_table(
  data=data,
  top_x=25,
  authors="authors"
)
@

<<fig.width=8, fig.height=3>>=
earliest_records_table(
  data=data,
  first=20,
  date="date",
  other_fields="accession strain country authors"
)
@

<<fig.width=8, fig.height=3>>=
latest_records_table(
  data=data,
  last=20,
  date="date",
  other_fields="accession strain country authors"
)
@


\end{document}