\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[margin=0.5in,top=1in,bottom=0.75in]{geometry}
\usepackage{amsmath}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage[table]{xcolor}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}

\usepackage{multicol}
\usepackage{graphicx}

\usepackage{fancyhdr}
\pagestyle{fancy}
\lhead{Nipah notes}
\rhead{last update: \today}

\begin{document}

<<,echo=FALSE>>=
#opts_chunk$set(fig.width=6,fig.height=3.5,size="footnotesize",fig.align='center',cache=FALSE,echo=TRUE)
opts_chunk$set(fig.width = 6, fig.height = 3.5, size = "footnotesize", fig.align = "center", cache = FALSE, echo = FALSE, warning=FALSE, message=FALSE)
@

<<message=FALSE, warning=FALSE>>=
source("shared_functions.R")
@


\section*{Background}

Nipah genome based on "Nipah Virus: Past Outbreaks and Future Containment" by Vinood Soman Pillai, Gayathri Krishna, and Mohanan Valiya Veettil Figure 1:

<<fig.width=8, fig.height=4>>=
# Download and decompress file
if (!file.exists("nipah/viruses-12-00465-g001-550.jpg")) {
  url <- "https://www.mdpi.com/viruses/viruses-12-00465/article_deploy/html/images/viruses-12-00465-g001-550.jpg"
  system("mkdir -p nipah")
  system(paste("curl -L", url, "-o nipah/viruses-12-00465-g001-550.jpg"))
}
@

\includegraphics[width=0.5\textwidth]{nipah/viruses-12-00465-g001-550.jpg}

<<fig.width=8, fig.height=4>>=
pathogen <- "nipah"

# Download and decompress file
data_file=paste0(pathogen, "/metadata.tsv")
if (!file.exists(paste0(pathogen,"/metadata.tsv"))) {
  system(paste0("mkdir -p ",pathogen))
  file_name <- "metadata.tsv"
  zst_file <- paste0(file_name, ".zst")
  url <- paste0("https://data.nextstrain.org/files/workflows/",pathogen,"/metadata.tsv.zst")
  system(paste0("curl -L ", url, " -o ", pathogen,"/", zst_file))
  system(paste0("zstd -d ",pathogen,"/", zst_file, " -o ", pathogen, "/", file_name))
}

data <- readr::read_delim(paste0(pathogen,"/metadata.tsv"), delim="\t")
@

\section*{NCBI GenBank records}

<<fig.width=8, fig.height=2.5>>=
diagnostic_length_plot(
  data = data,
  approx_length = 18200,
  binwidth = 200,
  percentage_y = 100
)
@

<<fig.width=8, fig.height=3.5>>=
diagnostic_time_fill_plot(
  data=data,
  fill="country"
  )
@

<<fig.width=8, fig.height=3>>=
earliest_records_table(
  data=data,
  first=10,
  date="date",
  other_fields="accession host country abbr_authors"
)
@

\noindent
"First identified [nipah] during an outbreak in Malaysia in humans and swine in 1998" from Wacharapluesadee, et al, 2021. Two decades of one health surveillance of Nipah virus in Thailand. One Health Outlook, 3, pp.1-14.


\noindent
\textbf{For further reading:}
\begin{itemize}
\item Chua, et al, 1999. Fatal encephalitis due to Nipah virus among pig-farmers in Malaysia. The Lancet, 354(9186), pp.1257-1259.
\end{itemize}

<<fig.width=8, fig.height=3>>=
top_x_author_table(
  data=data,
  top_x=25,
  authors="abbr_authors"
)
@





\end{document}