\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[margin=0.5in,top=1in,bottom=0.75in]{geometry}
\usepackage{amsmath}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage[table]{xcolor}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{hyperref}

\usepackage{multicol}
\usepackage{graphicx}

\usepackage{fancyhdr}
\pagestyle{fancy}
\lhead{WNV notes}
\rhead{last update: \today}

\begin{document}

<<,echo=FALSE>>=
#opts_chunk$set(fig.width=6,fig.height=3.5,size="footnotesize",fig.align='center',cache=FALSE,echo=TRUE)
opts_chunk$set(fig.width = 6, fig.height = 3.5, size = "footnotesize", fig.align = "center", cache = FALSE, echo = FALSE, warning=FALSE, message=FALSE)
@


<<message=FALSE, warning=FALSE>>=
library(tidyverse)
library(magrittr)
library(knitr)
library(kableExtra)
library(cowplot)
@

<<message=FALSE, warning=FALSE>>=
source("shared_functions.R")
@

\section*{Background}

CDC website: \url{https://www.cdc.gov/west-nile-virus/index.html}

\section*{Exploratory Graphics}

<<fig.width=8, fig.height=3>>=
# Download and decompress file
if (!file.exists("wnv/metadata.tsv")) {
  system("mkdir -p wnv")
  file_name <- "metadata.tsv"
  zst_file <- paste0(file_name, ".zst")
  url <- paste0("https://data.nextstrain.org/files/workflows/wnv/metadata.tsv.zst")
  system(paste0("curl -L ", url, " -o ", "wnv/", zst_file))
  system(paste0("zstd -d wnv/", zst_file, " -o wnv/", file_name))
}

data <- readr::read_delim("wnv/metadata.tsv", delim="\t")
@

\subsection*{How long is the WNV genome?}

WNV is approximately 11k nt long. The samples pulled from NCBI GenBank have the following distribution of lengths. Mostly seeing two clusters--very short sequences or around the full genome length.

<<fig.width=8, fig.height=2.5>>=
diagnostic_length_plot(
  data = data,
  approx_length = 11000,
  binwidth = 200,
  percentage_y = 15000
)
@

\subsection*{How well sampled is WNV across time and space?}

<<fig.width=8, fig.height=4>>=
diagnostic_time_fill_plot(
  data,
  margin_l=0.5,
  fill="region"
  )
@

The earliest samples seem to be from 1931. However, these are EF631122 and EF631123 and are supposedly collected in Illinois, USA, much earlier than the NY99 event. We might need to dig into publications that contain these GenBanks to check if this collection date is correct. Such as publication:

\begin{itemize}
\item Amore, G., Bertolotti, L., Hamer, G.L., Kitron, U.D., Walker, E.D., Ruiz, M.O., Brawn, J.D. and Goldberg, T.L., 2010. Multi-year evolutionary dynamics of West Nile virus in suburban Chicago, USA, 2005–2007. Philosophical Transactions of the Royal Society B: Biological Sciences, 365(1548), pp.1871-1878.
\end{itemize}

\subsection*{What lineages are available for WNV?}

\begin{itemize}
\item \textbf{Global lineage system:} Koch, R. Tobias, Diana Erazo, Arran J. Folly, Nicholas Johnson, Simon Dellicour, Nathan D. Grubaugh, and Chantal BF Vogels. "Genomic epidemiology of West Nile virus in Europe." One Health (2023): 100664.
\item \textbf{USA-based system:} Hadfield, J., Brito, A.F., Swetnam, D.M., Vogels, C.B., Tokarz, R.E., Andersen, K.G., Smith, R.C., Bedford, T. and Grubaugh, N.D., 2019. Twenty years of West Nile virus spread and evolution in the Americas visualized by Nextstrain. PLoS pathogens, 15(10), p.e1008042.
\end{itemize}

<<fig.width=8, fig.height=3.5>>=
diagnostic_time_fill_plot(
  data,
  margin_l=0.5,
  fill="lineage",
  title="Global lineage"
  )
@

<<fig.width=8, fig.height=3.5>>=
cdata <- data %>%
  subset(., !is.na(date)) %>%
  subset(., date !="XXXX-XX-XX") %>%
  dplyr::mutate(
    date_adjusted = lubridate::date(gsub("-XX", "-01", date)),
    col_year = substr(date, 1, 4),
    col_mon = substr(date, 6, 7),
    col_day = substr(date, 9, 10)
  )

diagnostic_time_fill_plot(
  data,
  margin_l=0.5,
  fill="clade_membership",
  title="Count of USA-based lineage samples with collection date"
  )
@

\newpage

\section*{Global subsampling}

If min length is set to 80 percent, or 8800nt:

<<fig.width=8, fig.height=3>>=
min_length <- 8800

filtered <- data %>% 
  subset(., length>min_length)
@

<<fig.width=8, fig.height=6>>=
data %>%
  subset(., !is.na(country)) %>%
  mutate(is_high = country %in% c("USA", "Italy")) %>%
  #subset(., country != "USA") %>%
  mutate(filter=length>min_length) %>%
  ggplot(., aes(x=country, fill=filter)) + 
  geom_bar() +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle=90, vjust=0.5, hjust=1),
    legend.position = "bottom",
    legend.title = element_blank()
  ) +
  labs(
    title=paste("WNV entries that were above or below filter, by country (n = ",nrow(subset(data, length>min_length))," where min-length=", min_length,")", sep=""),
    x="Year", y="Count"
  ) +
  scale_fill_manual(values = c("TRUE" = "#619CFF", "FALSE" = "#F8766D"),
                    labels = c("TRUE" = "Above length filter", "FALSE" = "Below length filter"))+
  facet_grid(is_high~., scales = "free",
             labeller = as_labeller(c("TRUE" = "Highs", "FALSE" = "Lows"))) #+
  #scale_grid_manual(labels = c("TRUE" = "Highs", "FALSE" = "Lows"))
@


\begin{itemize}
\item Total WNV records = \Sexpr{nrow(data)}. Note how this includes records without collection date
\item Total WNV records that passes the length filter = \Sexpr{nrow(filtered)}
\end{itemize}

If this number is lower than 4k, probably don't need to sub sample further.

\newpage

\subsection*{Who are the main submitters of sequence data?}


<<fig.width=8, fig.height=6>>=
top_x_author_table(data, top_x=25)
@

\newpage

\subsection*{What hosts are represented?}

<<fig.width=8, fig.height=3>>=
diagnostic_time_fill_plot(
  data,
  margin_l=0.5,
  fill="host_type",
  title="Host samples with collection date"
  )

count_hosts <- data %>%
  group_by(host_type) %>%
  summarise(
    n = n(),
  ) %>%
  arrange(desc(n))

kable(count_hosts, caption = paste("Host counts", sep="")) %>%
  kable_styling(latex_options = c("hold_position", "striped"))
@


\end{document}